# Generated by Django 2.2.10 on 2020-12-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20201227_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='owner',
        ),
    ]
